[toolchain]
# Old version of Anchor used 'yarn'
# See https://www.anchor-lang.com/docs/updates/release-notes/0-31-0
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "6zSSLr3UjdtLcLXRrCSvJAvRHdFbbMnkBjxagfttFR2r"

[programs.devnet]
escrow = "6zSSLr3UjdtLcLXRrCSvJAvRHdFbbMnkBjxagfttFR2r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx create-codama-client.ts; npx tsx --test --test-reporter=spec tests/*.ts && npx tsx confetti.ts"
